- name: Get details about installed packages
  ansible.builtin.package_facts:
- name: nginx-octoprint config
  ansible.builtin.copy:
    src: files/nginx-default-octoprint.conf
    dest: /etc/nginx/sites-available/default-octoprint.conf
    owner: root
    group: root
    mode: "0644"
  notify: restart-nginx
  when: ansible_facts["packages"]["nginx"] is defined
- name: caddy-octoprint config
  ansible.builtin.copy:
    src: files/octoprint.caddy
    dest: /etc/caddy/conf.d/octoprint.caddy
    owner: root
    group: root
    mode: "0644"
  notify: restart-caddy
  when: ansible_facts["packages"]["caddy"] is defined
