- name: package install
  ansible.builtin.import_tasks: packages.yml
- name: pendant install
  ansible.builtin.import_tasks: tinyweb.yml
- name: cncjs webserver config
  ansible.builtin.import_tasks: webserver.yml
- name: cncjs service
  ansible.builtin.import_tasks: service.yml
