- name: nodejs and required modules
  apt:
    name:
    - nodejs
    - npm
- name: cncjs package
  npm:
    global: yes
    name: "cncjs@1.10.5"
    unsafe_perm: yes
- name: cncjs watch directory
  file:
    path: /home/js/watch
    state: directory
    owner: js
    group: js
    mode: "0755"
