- name: nodejs and required modules
  ansible.builtin.apt:
    name:
    - nodejs
    - npm
- name: cncjs package
  ansible.builtin.npm:
    global: yes
    name: "cncjs@1.11.0"
    unsafe_perm: yes
- name: cncjs watch directory
  ansible.builtin.file:
    path: "/home/{{ cncjs_user }}/watch"
    state: directory
    owner: "{{ cncjs_user }}"
    group: "{{ cncjs_group }}"
    mode: "0755"
