- name: daemon-reload
  systemd:
    daemon_reload: true
- name: restart-nginx
  service:
    name: nginx
    state: restarted
- name: restart-octoprint
  service:
    name: octoprint
    state: restarted
